env: standard
runtime: nodejs16
instance_class: F1
service: default

handlers:
  - url: /_next/static
    static_dir: .next/static
  - url: /(.*\.(gif|png|jpg|ico|txt|svg|pdf))$
    static_files: public/\1
    upload: public/.*\.(gif|png|jpg|ico|txt|svg|pdf)$
  - url: /.*
    script: auto
    secure: always

default_expiration: "12h"

automatic_scaling:
  min_instances: 0
  max_instances: 3
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: 3s
