steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$${SSH_KEY}" > /root/.ssh/id_ed25519
        chmod 400 /root/.ssh/id_ed25519
        echo "${_GITHUB_HOST_KEY}" >> /root/.ssh/known_hosts
        echo "$${MICROCMS_SECRET}" > .env
    secretEnv:
      - SSH_KEY
      - MICROCMS_SECRET
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'gcr.io/cloud-builders/git'
    args:
      - submodule
      - update
      - '--init'
      - '--remote'
      - '--recursive'
    volumes:
    - name: 'ssh'
      path: /root/.ssh

  - name: 'node:18'
    entrypoint: yarn
    args:
      - install

  - name: 'node:18'
    entrypoint: yarn
    args:
      - build

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - deploy
      - app.yaml
      - '--quiet'

availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/SSH_KEY/versions/latest
    env: SSH_KEY
  - versionName: projects/${PROJECT_ID}/secrets/MICROCMS/versions/latest
    env: MICROCMS_SECRET
