#:schema node_modules/wrangler/config-schema.json
name = 'blog'
main = '.worker-next/index.mjs'

compatibility_date = '2024-09-26'
compatibility_flags = ['nodejs_compat']

# Minification helps to keep the Worker bundle size down and improve start up time.
minify = true

# Use the new Workers + Assets to host the static frontend files
assets = { directory = '.worker-next/assets', binding = 'ASSETS' }

# Bind a KV Namespace. Use KV as persistent storage for small key-value pairs.
# Docs: https://developers.cloudflare.com/workers/wrangler/configuration/#kv-namespaces
[[kv_namespaces]]
binding = 'NEXT_CACHE_WORKERS_KV'
id = 'd975e5d11f334fca9096083aedf638cc'
