name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v4
        with:
          lfs: true
          ssh-key: ${{ secrets.SSH_KEY }}
          submodules: recursive

      - name: Setup node env 🏗
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          check-latest: true

      - name: Install dependencies 👨🏻‍💻
        run: yarn install --frozen-lockfile

      - name: Run linter 👀
        run: yarn lint

      - name: Run build 🏗
        run: yarn build
        env:
          MICROCMS_API_HOST: ${{ secrets.MICROCMS_API_HOST }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
          MICROCMS_SECRET: ${{ secrets.MICROCMS_SECRET }}
