name: Deploy
on:
  push:
    branches: ['master']
    tags: ['v*.*.*']
    paths-ignore:
      - '*.md'
      - '.*.y[a]?ml'
      - '.github/*.y[a]?ml'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.*.y[a]?ml'
      - '.github/*.y[a]?ml'
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    permissions:
      actions: write # Required for deleting old cache
      contents: read
      packages: write

    strategy:
      matrix:
        target: ['prod', 'dev']

    uses: ./.github/workflows/bake.yml
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      node_version: ${{ vars.NODE_VERSION }}
      variant: ${{ vars.VARIANT }}
      environment: ${{ matrix.target }}
      push: ${{ github.event_name != 'pull_request' }}

      registry: ${{ vars.REGISTRY }}

    secrets:
      registry_user: ${{ secrets.REGISTRY_USER }}
      registry_password: ${{ secrets.REGISTRY_TOKEN }}

      ssh_key: ${{ secrets.SSH_KEY }}

      microcms_service_domain: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
      microcms_api_key: ${{ secrets.MICROCMS_API_KEY }}
      microcms_secret: ${{ secrets.MICROCMS_SECRET }}
