name: release

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
        with:
          ssh_key: ${{ secrets.SSH_KEY }}

      - name: Setup PGP 🔑
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Create Pull Request 🚀
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          title: Release
          labels: Auto-PR
          branch: bot/staging
          assignees: ${{ github.actor }}
          author: kotokaze <62094392+kotokaze@users.noreply.github.com>
          branch-suffix: short-commit-hash
          base: release
          delete-branch: true

      - name: Check for changes 🔎
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
