name: submodules

on:
  workflow_dispatch:

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2
        with:
          lfs: true
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Fetch submodules 🚚
        run: git submodule update --init --recursive --remote

      - name: Setup PGP 🔑
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Create Pull Request 🚀
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          title: Update submodules
          labels: Auto-PR
          base: master
          branch: bot/update-submodules
          branch-suffix: short-commit-hash
          delete-branch: true
          author: kotokaze <62094392+kotokaze@users.noreply.github.com>
          commit-message: ':recycle: Fetch latest submodules'

      - name: Check for changes 🔎
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
